package ServerObjectInterfaceApp;

/**
 * ServerObjectInterfaceApp/ServerObjectInterfaceHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ServerObjectInterface.idl
 * Friday, February 28, 2020 4:30:32 PM EST
 */

public final class ServerObjectInterfaceHolder implements org.omg.CORBA.portable.Streamable {
    public ServerObjectInterfaceApp.ServerObjectInterface value = null;

    public ServerObjectInterfaceHolder() {
    }

    public ServerObjectInterfaceHolder(ServerObjectInterfaceApp.ServerObjectInterface initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = ServerObjectInterfaceApp.ServerObjectInterfaceHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        ServerObjectInterfaceApp.ServerObjectInterfaceHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return ServerObjectInterfaceApp.ServerObjectInterfaceHelper.type();
    }

}
