package ServerObjectInterfaceApp;


/**
 * ServerObjectInterfaceApp/ServerObjectInterface.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from ServerObjectInterface.idl
 * Friday, February 28, 2020 4:30:32 PM EST
 */

public interface ServerObjectInterface extends ServerObjectInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface ServerObjectInterface
